version: "3.6"
services:
  # PostgreSQL
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_URL: postgres://admin:password@localhost:5432/pizzaria
      POSTGRES_DB: pizzaria
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
  # api:
  #   build:
  #     context: ./api
  #     target: dev
  #   volumes:
  #     - ./api:/api
  #   ports:
  #     - "3333:3333"
  #   links:
  #     - postgres
  #   depends_on:
  #     - postgres
